name: 'Starlify Action'
description: 'A GitHub Action that connects your repo to Starlify'
author: 'Entiros AB'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'star'
  color: 'green'

# Define your inputs here.
inputs:
  api_key:
    description: 'Your Starlify API key'
    required: true
  workspace_id:
    description: 'Your Starlify workspace ID'
    required: true
  github_token:
    description: 'Your GitHub token'
    required: true

# Define your outputs here.
outputs:
  url:
    description: 'The URL of the created Starlify references'

runs:
  using: node20
  main: dist/index.js
